apiVersion: v1
kind: Service
metadata:
  name: student-backend-service
spec:
  selector:
    app: student-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer  # To expose it on the internet
