apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  mongo_url: "mongodb+srv://olamiwalepaul:lZ0v985kVWPMI87J@cluster0.ayxxdqm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
